#
# Module manifest for module 'psgigr'
#
# Generated by: gian.grueninger
#
# Generated on: 27.07.2023
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'aa0e4c88-2f8f-4cac-bb4b-c8bef7224027'

# Author of this module
Author = 'Gian Grüninger'

# Company or vendor of this module
CompanyName = 'Self'

# Copyright statement for this module
Copyright = '(c) Gian Grüninger. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powershell Module by Gian'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.0'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = '5.0'

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Set-WebPartExportMode'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

#-----------------------------------------------
#--------- define private funktions ------------
#-----------------------------------------------
function Install-SharepointOnlineModule {
    #Define the name of the module you want to check/install
    $ModuleName = "Microsoft.Online.SharePoint.PowerShell"

    # Check if the module is already installed
    if (Get-Module -ListAvailable -Name $ModuleName) {
            Write-Host "The '$ModuleName' module is already installed."
    }
    else {
        Write-Host "The '$ModuleName' module is not installed. Installing..."
        
        # Try to install the module using the PowerShellGet module (requires PowerShell 5.0+)
        try {
            Install-Module -Name $ModuleName -Force -AllowClobber -Scope CurrentUser -ErrorAction Stop
            Write-Host "Module '$ModuleName' has been installed successfully."
        }
        catch {
            Write-Host "Failed to install the module '$ModuleName'. Error: $_"
        }
    }    
}

#-----------------------------------------------
#---------- define public funktions ------------
#-----------------------------------------------
function Set-WebpartExportMode {
    <#
        .Synopsis
        Fixes the Veeam M365 Backup error. Cannot Change Web Part Export Mode.

        .Description
        Automatically fixes the error.

        .PARAMETER LogEntry
        Paste here the complete Veeam M365 Backup error.

        .Example
        # Input example
        Show-Calendar
    #>
    param (
        [Parameter(Mandatory=$true)]
        [string]$logEntry
    )

    # Define a regular expression pattern to match the site URL
    $pattern = "https:\/\/([^.]+\.sharepoint\.com)\/sites\/([^/\s]+)"

    # Use the Select-String cmdlet to find matches based on the pattern
    $patternmatches = $logEntry | Select-String -Pattern $pattern -AllMatches | ForEach-Object { $_.Matches }

    # Loop through each match and print the results
    foreach ($match in $patternmatches) {
        $siteURL = $match.Groups[0].Value
        $siteName = $match.Groups[2].Value
    }

    # Define the regular expression pattern to match the domain in the source URL
    $pattern = "(https?://)([^/]+?)(?:-admin)?(\.sharepoint\.com)/.*"

    # Use the regular expression to replace the domain and everything after ".com/" in the source URL
    $adminUrl = [regex]::Replace($SiteUrl, $pattern, "`$1`$2-admin`$3/")

    #Modul Installieren falls nötig
    Install-SharepointOnlineModule

    Connect-SPOService -Url $adminurl
    Set-SPOSite $siteURL -DenyAddAndCustomizePages 0
    try {
        Write-Host "Site $siteurl successfully updated"
    }
    catch {
        Write-Host "Site $sitename not updated, error"
    }
}